#!/usr/bin/make -f
SHELL = /bin/bash

OS := $(shell uname)
#bin_list := npm node
bin_list := node npm ls
bin_paths := $(foreach bin,$(bin_list),$(shell which $(bin)))
#bin_list_count := $(strip $(shell echo $(bin_list) | wc -w))
#bin_path_count := $(strip $(shell echo $(bin_paths) | wc -w))
bin_list_count := $(words $(bin_list))
bin_path_count := $(words $(bin_paths))

all: verify_all
	@echo "Doing ALL!.."

show_stuff:
	$(error this is the error message that will stop the build process)
	$(warning this the warning msg)
	$(info this the info msg)

verify_all: verify_bins

define say_something
    echo "You said "$(1)
endef

check: verify_all

verify_bins:
ifeq ($(shell test $(bin_list_count) -gt $(bin_path_count); echo $$?),0)
	@echo "Not all bins found"
else
	@echo "All bins found"
endif
	$(info Binary Files Required ($(bin_list_count)): $(bin_list))
	$(info Binary Files Found ($(bin_path_count)): $(bin_paths))

.PHONY: all

